[package]
name = "codegen-test"
description = "Crate that tests the Smithy codegen plugin"
version.workspace = true
publish = false
edition.workspace = true
license.workspace = true

[build-dependencies]
smithy-cargo = "1.1.0"

[dependencies]
smithy4rs-core.workspace = true