[versions]
junit5 = "6.0.0"
hamcrest = "3.0"
smithy = "1.63.0"
smithy-gradle = "1.3.0"
test-logger-plugin = "4.0.0"
spotbugs = "6.4.4"
spotless = "8.0.0"
dep-analysis = "3.3.0"

[libraries]
# Smithy deps
smithy-codegen = { module = "software.amazon.smithy:smithy-codegen-core", version.ref = "smithy" }
smithy-build = { module = "software.amazon.smithy:smithy-build", version.ref = "smithy" }
smithy-utils = { module = "software.amazon.smithy:smithy-utils", version.ref = "smithy" }

# Test dependencies
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
hamcrest = { module = "org.hamcrest:hamcrest", version.ref = "hamcrest" }

# plugin artifacts for buildsrc plugins
test-logger-plugin = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "test-logger-plugin" }
spotbugs = { module = "com.github.spotbugs.snom:spotbugs-gradle-plugin", version.ref = "spotbugs" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
dependency-analysis = { module = "com.autonomousapps:dependency-analysis-gradle-plugin", version.ref = "dep-analysis" }

