[package]
name = "smithy4rs-core"
description = "Core functionality for smithy4rs."
repository.workspace = true
publish = true
readme.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
num-bigint.workspace = true
bigdecimal.workspace = true
bytebuffer.workspace = true
indexmap.workspace = true
thiserror.workspace = true
downcast-rs.workspace = true
regex.workspace = true
fast-str.workspace = true
temporal_rs.workspace = true

pastey = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
static_str_ops = "0.1.2"
rustc-hash = "2.1.1"

[dev-dependencies]
serde_json = "1.0.148"
smithy4rs-core-derive.workspace = true
smithy4rs-test-utils.workspace = true
criterion.workspace = true

[lints]
workspace = true

[[bench]]
name = "schema"
harness = false

[[bench]]
name = "validation"
harness = false