name: publish-codegen.yml
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: Build and Release Java Codegen packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build and test
        working-directory: codegen
        run: ./gradlew build test

      - name: Publish to Local Maven Staging
        working-directory: codegen
        run: ./gradlew publish --stacktrace --info

      - name: Release
        working-directory: codegen
        env:
          JRELEASER_GENERIC_TOKEN: ${{ secrets.JRELEASER_GENERIC_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_USER }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_PASS }}
        run: ./gradlew jreleaserRelease --no-configuration-cache